### ISSUE TITLE
.chat command

### ISSUE THREAD

**Issue by Redo11** [fuzzbuck/mindustry.io-plugin#17]
welp 
.chat .
[Enter][Enter][Enter][Enter][Enter][Enter][Enter][Enter][Enter][Enter][Enter][Enter][Enter][Enter]
works and it shouldn't as it spams everyones screen. Discord messages should also have banned colours as its easy to imitate someone.
Sorry that i had to test it on your server. Good work, Fuzzie!(and contributors)

**Comment by DeltaNedas** [comment]
we just caught zacbytes (or you idk) spamming it 200 times in last 10 mins...

**Comment by Redo11** [comment]
i did use it, but not spammed like this idiot

**Comment by Redo11** [comment]
but its my fault as i showed it to him and everyone

**Comment by Redo11** [comment]
while error=0
replace [enter][enter] --> [enter]

Replace 2 enters to one until operation is unsuccessful, what means that there are no more double enters
Error 0 = No errors
Error >1 = Errors and others, unsuccessful
Idk how to write code, but this might be helpful

**Comment by DeltaNedas** [comment]
s/\n{2,}/\n/g

**Comment by Volas171** [comment]
Umm it's fixable but is gonna need to ban space

**Comment by fuzzbuck** [comment]
going to be fixed in v103 release, thanks for reporting 👍

**Comment by Volas171** [comment]
Lel

**Comment by CA6** [comment]
It was you're fault.....  nice
