### ISSUE TITLE
Um..... Help?

### ISSUE THREAD

**Issue by Erisfiregamer1** [fuzzbuck/mindustry.io-plugin#18]
I recently started using the BE build instead of the itch.io builds. Now, I cant play. HELP! Please make a server for BE builds!

**Comment by DeltaNedas** [comment]
.io is on 102.3
you having a bleeding edge version is not fuzz' fault.

**Comment by Redo11** [comment]
you see. you can git older versions. its one attribute. use man git and do not shit post it as an issue  make suggestion out of this. Heres discord, with dedicated channel to shitposting(#sugesstions) discord.mindustry.io. Have fun.
