### ISSUE TITLE
Find a better way of storing PlayerData

### ISSUE THREAD

**Issue by fuzzbuck** [fuzzbuck/mindustry.io-plugin#24]
Java's serialization is terrible, I'm looking towards a more 1 big centralized database approach, where 4 servers will share ranks & stuff.

TempPlayerData can remain untouched.

**Comment by DeltaNedas** [comment]
just use a big json file

**Comment by fuzzbuck** [comment]
> 
> 
> just use a big json file

unoptimal, 4+ servers are going to potentially read & write to that file a couple times per second

**Comment by DeltaNedas** [comment]
no
first load it in a daemon that uses dbus or something to do reads and writes in memory
then save it when all servers are down
problem solved with only one read and write on disk

**Comment by fuzzbuck** [comment]
> 
> 
> no
> first load it in a daemon that uses dbus or something to do reads and writes in memory
> then save it when all servers are down
> problem solved with only one read and write on disk

what if the server happens to crash?

**Comment by DeltaNedas** [comment]
then nothing happens
if all servers crash, daemon will stop and save data to disk

**Comment by DeltaNedas** [comment]
if you mean the server itself being bombed by isis or something then save it at an interval like every minute on a separate thread

**Comment by J-VdS** [comment]
you could also move to sqlite or sql

**Comment by DeltaNedas** [comment]
but its slow and uses lots of disk

**Comment by fuzzbuck** [comment]
> 
> 
> but its slow and uses lots of disk

seems more reliable tho

**Comment by DeltaNedas** [comment]
true

**Comment by DeltaNedas** [comment]
but it will constantly be accessed by every server so relying on disk for all operations is bad

**Comment by ado1928** [comment]
Well, you can open the file, write to it, then close it right afterwards. That'd take miliseconds and the probability of a file being open when another server is writing is very small. But add a try block just in case

**Comment by fuzzbuck** [comment]
I will try this:
https://www.aerospike.com/docs/client/java/

will reply soon with results (how well it works, etc.)
