### ISSUE TITLE
Ping spikes

### ISSUE THREAD

**Issue by fuzzbuck** [fuzzbuck/mindustry.io-plugin#33]
So far only reported on PVP, server sometimes goes up to 50000ms ping and drops back to normal, case unknown.

Find cause & fix.

**Comment by Blockzilla101** [comment]
What if someone is ddos/dos ing the server? Is there a way to find out?

**Comment by ado1928** [comment]
If so, what if fuzz sets a data limit for every ip. 8mbps would be enough for a mindustry server per connection

**Comment by ado1928** [comment]
Also: https://www.hetzner.com/unternehmen/ddos-schutz

**Comment by Blockzilla101** [comment]
Worth a try, If it does nothing then something else is wrong like the server getting stuck in some function or the jedis database is not able to give a response to the servers request fast enough because of another server's requests backlog.

**Comment by fuzzbuck** [comment]
> 
> 
> What if someone is ddos/dos ing the server? Is there a way to find out?

The server is not being ddosed, outgoing & incoming traffic remains the same during ping spikes.

**Comment by ado1928** [comment]
I'll play on pvp for a while and try to notice any patterns for the spikes

**Comment by DeltaNedas** [comment]
its not ddos
server is doing a fuck ton of work cpu wise and it slowed down
fuzz pls use a profiler and find what function takes most time

**Comment by Blockzilla101** [comment]
if all 4 mindustry.io servers run on the same cpu then ping spike shouldnt be expected on all servers?

**Comment by Blockzilla101** [comment]
> server is doing a fuck ton of work cpu wise and it slowed down
if all 4 servers are running on the same cpu then shouldn't the spike be in all 4 servers?

**Comment by Blockzilla101** [comment]
what if the database processs is saving the database and that moment server made a some of requests and its waiting for the replies?

**Comment by DeltaNedas** [comment]
if true, my suggestion of keeping all data in memory and only doing i/o on a separate thread or when all servers exit would be better

**Comment by not-purple** [comment]
Can you try by disable some functions and try to figure whether it or not causing ping spike.

**Comment by ado1928** [comment]
well, he can't reproduce ping spikes, it would be boring to just sit and watch for ping spikes.

**Comment by not-purple** [comment]
What if using the dev.mindustry.io, and try lagging the database. (simulate lot of i/o event)

**Comment by fuzzbuck** [comment]
some retard is ddosing the servers every now and then
